PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 52.35.201.130.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    GHE:
    - Name: GHE
      Url: https://github.ablevets.com/api/v3/
    Global:
      EnvVars:
        DOCKER_REGISTRY: 553057676898.dkr.ecr.us-west-2.amazonaws.com
        TILLER_NAMESPACE: kube-system
prow: {}
